name: Release Application

on:
  push:
    branches:
      - "**" # LET THE PIPELINE TRIGGER ON A PUSH TO ALL BRANCHES
  release:
    types: [published]

env: # ADD YOUR ENVIRONMENT VARIABLES HERE
  openshift_token: ${{ secrets.OPENSHIFT_API_TOKEN }}
  openshift_url: https://api.rm1.0a51.p1.openshiftapps.com:6443

jobs:
  deploy:
    if: github.ref == 'refs/heads/dev' # ADD YOUR CONDITION HERE
    environment: development
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.rm1.0a51.p1.openshiftapps.com:6443
          openshift_token: ${{ secrets.OPENSHIFT_API_TOKEN }}
          namespace: brampelberg-dev

      - name: Apply Openshift YAML
        run: |
          oc apply -f infra/openshift.yaml
